profs = {
    1: "Guardian",
    2: "Warrior",
    3: "Engineer",
    4: "Ranger",
    5: "Thief",
    6: "Elementalist",
    7: "Mesmer",
    8: "Necromancer",
    9: "Revenant"
    }

elites = {
    5:  "Druid",
    7:  "Daredevil",
    18: "Berserker",
    27: "Dragonhunter",
    34: "Reaper",
    40: "Chronomancer",
    43: "Scrapper",
    48: "Tempest",
    52: "Herald",
    55: "Soulbeast",
    56: "Weaver",
    57: "Holosmith",
    58: "Deadeye",
    59: "Mirage",
    60: "Scourge",
    61: "Spellbreaker",
    62: "Firebrand",
    63: "Renegade",
    64: "Harbinger",
    65: "Willbender",
    66: "Virtuoso",
    67: "Catalyst",
    68: "Bladesworn",
    69: "Vindicator",
    70: "Mechanist",
    71: "Specter",
    72: "Untamed"
    }

prof_abbrv = {
    "Guardian": "Gdn",
    "Dragonhunter": "Dgh",
    "Firebrand": "Fbd",
    "Willbender": "Wbd",
    "Warrior": "War",
    "Berserker": "Brs",
    "Spellbreaker": "Spb",
    "Bladesworn": "Bds",
    "Engineer": "Eng",
    "Scrapper": "Scr",
    "Holosmith": "Hls",
    "Mechanist": "Mec",
    "Ranger": "Rgr",
    "Druid": "Dru",
    "Soulbeast": "Slb",
    "Untamed": "Unt",
    "Thief": "Thf",
    "Daredevil": "Dar",
    "Deadeye": "Ded",
    "Specter": "Spe",
    "Elementalist": "Ele",
    "Tempest": "Tmp",
    "Weaver": "Wea",
    "Catalyst": "Cat",
    "Mesmer": "Mes",
    "Chronomancer": "Chr",
    "Mirage": "Mir",
    "Virtuoso": "Vir",
    "Necromancer": "Nec",
    "Reaper": "Rea",
    "Scourge": "Scg",
    "Harbinger": "Har",
    "Revenant": "Rev",
    "Herald": "Her",
    "Renegade": "Ren",
    "Vindicator": "Vin"
    }

prof_colors = {
    "Guardian":     "#00ccff",
    "Warrior":      "#ffcc33",
	"Engineer":     "#cc6633",
	"Ranger":       "#99cc00",
	"Thief":        "#cc6666",
	"Elementalist": "#ff3333",
	"Mesmer":       "#cc33cc",
	"Necromancer":  "#00cc66",
	"Revenant":     "#993333"
    }

team_ids = {
        697:  "Red", 705:  "Red", 706:  "Red", 882:  "Red", 2520: "Red",
        39:   "Green", 2739: "Green", 2741: "Green", 2752: "Green", 2763: "Green",
        432:  "Blue", 1277: "Blue", 1989: "Blue"
    }

elite_profs = {
    "Dragonhunter":    "Guardian",
    "Firebrand":       "Guardian",
    "Willbender":      "Guardian",
    "Guardian":        "Guardian",
    "Berserker":       "Warrior",
    "Spellbreaker":    "Warrior",
    "Bladesworn":      "Warrior",
    "Warrior":         "Warrior",
    "Scrapper":        "Engineer",
    "Holosmith":       "Engineer",
    "Mechanist":       "Engineer",
    "Engineer":        "Engineer",
    "Druid":           "Ranger",
    "Soulbeast":       "Ranger",
    "Untamed":         "Ranger",
    "Ranger":          "Ranger",
    "Daredevil":       "Thief",
    "Deadeye":         "Thief",
    "Specter":         "Thief",
    "Thief":           "Thief",
    "Tempest":         "Elementalist",
    "Weaver":          "Elementalist",
    "Catalyst":        "Elementalist",
    "Elementalist":    "Elementalist",
    "Chronomancer":    "Mesmer",
    "Mirage":          "Mesmer",
    "Virtuoso":        "Mesmer",
    "Mesmer":          "Mesmer",
    "Reaper":          "Necromancer",
    "Scourge":         "Necromancer",
    "Harbinger":       "Necromancer",
    "Necromancer":     "Necromancer",
    "Herald":          "Revenant",
    "Renegade":        "Revenant",
    "Vindicator":      "Revenant",
    "Revenant":        "Revenant"
    }